// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Answer
{
    public int AnswerId { get; set; }

    public string Body { get; set; }

    public int? PostedBy { get; set; }

    public int? QuestionId { get; set; }

    public DateTime? DatePosted { get; set; }

    public bool? IsAccepted { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User PostedByNavigation { get; set; }

    public virtual Question Question { get; set; }

    public virtual ICollection<Vote> Votes { get; set; } = new List<Vote>();
}