// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Badge
{
    public int BadgeId { get; set; }

    public string BadgeName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<UserBadge> UserBadges { get; set; } = new List<UserBadge>();
}