// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Comment
{
    public int CommentId { get; set; }

    public string Body { get; set; }

    public int? PostedBy { get; set; }

    public int? QuestionId { get; set; }

    public int? AnswerId { get; set; }

    public DateTime? DatePosted { get; set; }

    public virtual Answer Answer { get; set; }

    public virtual User PostedByNavigation { get; set; }

    public virtual Question Question { get; set; }
}