// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Question
{
    public int QuestionId { get; set; }

    public string Title { get; set; }

    public string Body { get; set; }

    public int? PostedBy { get; set; }

    public int? CategoryId { get; set; }

    public DateTime? DatePosted { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    public virtual User PostedByNavigation { get; set; }

    public virtual ICollection<Vote> Votes { get; set; } = new List<Vote>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}