// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Tag
{
    public int TagId { get; set; }

    public string TagName { get; set; }

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();
}