// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class UserBadge
{
    public int UserId { get; set; }

    public int BadgeId { get; set; }

    public DateTime? DateAwarded { get; set; }

    public virtual Badge Badge { get; set; }

    public virtual User User { get; set; }
}