// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp2.Models;

public partial class Vote
{
    public int VoteId { get; set; }

    public string Type { get; set; }

    public int? UserId { get; set; }

    public int? QuestionId { get; set; }

    public int? AnswerId { get; set; }

    public DateTime? DateVoted { get; set; }

    public virtual Answer Answer { get; set; }

    public virtual Question Question { get; set; }

    public virtual User User { get; set; }
}